test_01:
	python src/academic/driver/Driver1.py 12S2203 "Object-oriented Programming" 3 C

test_02:
	python src/academic/driver/Driver1.py 10S1002 "Pemrograman Prosedural" 2 D

test_03:
	python src/academic/driver/Driver2.py 12S20999 "Wiro Sableng" 2020 "Information Systems"

test_04:
	python src/academic/driver/Driver2.py 12S20111 "Jaka Sembung" 2019 "Information Systems"

test_05:
	python src/academic/driver/Driver3.py


.PHONY: test_01 test_02 test_03 test_04

set_path:
	set PYTHONPATH=D:\GitHub\PBO Python Edition\2324-ge-t01-deja-vu-WinfreyNainggolan01\src


