# compile :
# 	javac src/academic/model/*.java src/academic/driver/*.java -d bin

# test_01 :
# 	cd bin && java academic.driver.Driver1

# test_02 :
# 	cd bin && java academic.driver.Driver2

# test_03 :
# 	cd bin && java academic.driver.Driver3

# test_04 :
# 	cd bin && java academic.driver.Driver4

test_01:
	python src/academic/driver/Driver1.py

test_02:
	python src/academic/driver/Driver2.py 

test_03:
	python src/academic/driver/Driver3.py

test_04:
	python src/academic/driver/Driver4.py

set:
	set PYTHONPATH=D:\GitHub\PBO Python Edition\2324-ge-t02-academic-simulator-WinfreyNainggolan01\src
	


