test_01:
	python src/academic/driver/Driver1.py

test_02:
	python src/academic/driver/Driver2.py 

set:
	set PYTHONPATH=D:\GitHub\PBO Python Edition\2324-ge-t06-remedial-6e0ef14b-WinfreyNainggolan01\src