# compile :
# 	javac src/academic/model/*.java src/academic/driver/*.java -d bin

# test_01 :
# 	cd bin && java academic.driver.Driver1

# test_02 :
# 	cd bin && java academic.driver.Driver2
# compile :
# 	javac src/academic/model/*.java src/academic/driver/*.java -d bin



test_01:
	python src/academic/driver/Driver1.py

test_02:
	python src/academic/driver/Driver2.py 

set:
	set PYTHONPATH=D:\GitHub\PBO Python Edition\2324-ge-t03-data-integrity-WinfreyNainggolan01\src
	
	


